enum GAPage: String {
  case login_page = "login_page"
  case nickname_initialize_page = "nickname_initialize_page"
  case nickname_change_page = "nickname_change_page"
  case home_page = "home_page"
  case main_page = "main_page"
  case store_list_page = "store_list_page"
  case store_detail_page = "store_detail_page"
  case review_write = "review_write"
  case store_register_page = "store_register_page"
  case store_edit_page = "store_edit_page"
  case delete_request_popup = "delete_request_popup"
  case my_info_page = "my_info_page"
  case setting_page = "setting_page"
}
