name: Swift

on:
  push:
    branches:
    - develop
    - master
  pull_request:
    branches:
    - develop
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        pod install --repo-update --clean-install
        xcodebuild test -workspace 3dollar-in-my-pocket.xcworkspace -scheme 3dollar-in-my-pocket -destination 'platform=iOS Simulator,name:iPhone 12 Pro,OS=14.4'
